VNG-Realisatie/nlx

CONTRIBUTING.md

Add a short message about OneFlow

---

README.md

Since we get some traffic from Google & Github it's good to show at first glance that this repository holds just a proof of concept.

Add badge to README.md as indicator for concept status

---

README.md

With apologies. Here some CI on the docs would help indeed. :)

Fix wrong relative link to product vision

---

CONTRIBUTING.md
README.md

Let's give people clear guidance on how to contribute to the project! Including, questions, issues, bugs code and documentation.
Closes #14 and #2.

A `CONTRIBUTING` file

---

docs/content/functional/compliancy.md
docs/content/functional/product-vision.md
docs/content/functional/solution-architecture.md

- Processed feedback from @ksbrwr, @BoerBas and more - thanks!
- Altered order of docs, Product Vision should (for now) come first
- Solution Architecture will most likely never be made, deleted
- Markdown doesn't do colspan, reformatted the compliancy document for readability

Update functional docs 

---

docs/content/functional/compliancy.md

Edit compliancy documents for layout

---

certportal/Dockerfile
certportal/Makefile
certportal/certportal.go
certportal/cmd/nlx-certportal/main.go
certportal/files/css/app.css
certportal/files/index.html
certportal/files/js/app.js
certportal/listen.go
certportal/modd.conf
docker-compose.yml

This pull request adds a new component which provides a portal to developers to request a NLX  development certificate.
This closes #45 .

A certificate portal for developers to easily request NLX development certificates

---

docs/content/contributing-to-nlx/functional-design.md

Initial list of functional specs based on the Product Vision, closes #5.
Obviously not all of this is relevant for Proof of Concept.

Add functional specs for NLX logging

---

docs/README.md

This simple PR mostly fixes what is broken in the meta documentation.

Documentation on the Documentation

---

directory/cmd/nlx-directory/main.go
directory/cmd/nlx-directory/server.go
docker-compose.yml
outway/outway.go

directory: Expose http/json API on a seperate port providing plain HTTP (no TLS).

---

directory-ui/Dockerfile

Fix problem with `npm install` of directory-ui #101

---

common/logoptions/logoptions.go
directory/cmd/nlx-directory/main.go
docker-compose.yml
inway/cmd/nlx-inway/main.go
outway/cmd/nlx-outway/main.go

fixes #103 
fixes VNG-Realisatie/field-lab#2

Add logging options

---

directory-ui/proxy.conf.json
directory-ui/src/app/app.component.html
directory-ui/src/app/service.ts

Correctly show service status

---

inway/endpoint.go

Correctly set Host header

---

README.md
docs/content/_index.md
docs/content/developing-on-nlx/building-an-application.md
docs/content/developing-on-nlx/creating-a-service.md
docs/content/introduction/logging.md
docs/content/introduction/security.md
inway/service-config.toml

This adds some explanation to the documentation and README.md and closes #128 and closes #136.

docs: some improvements

---

docs/README.md

I've tried to update the `docs` readme to be a bit clearer about how to actually edit the docs.
Fixes #156 
Conflicts with #193 due to the changing of a header in that PR.

Update `docs` README

---

directory-ui/src/polyfills.ts

Added polyfills to support IE9+

---

certportal/README.md
directory-ui/README.md

This closes #201 and closes #203

Added README.md for certportal and directory-ui

---

directory/README.md
inway/README.md
monitor/README.md
outway/README.md
unsafe-ca/Dockerfile
unsafe-ca/README.md

Fixes #200
Fixes #198
Fixes #202
Fixes #197

Add readme's to components inway, outway, directory, monitor, unsafe-ca

---

inway/inway.go

inway: re-register to directory every 10 seconds
